/**
 * @file test_dynamic.c
 *
 * @author jeff.daily@pnnl.gov
 *
 * Copyright 2012 Pacific Northwest National Laboratory. All rights reserved.
 */
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "constants.h"
#include "dynamic.h"

static const char seq0[] = 
"MMVLEIRNVAVIGAGSMGHAIAEVVAIHGFNVKLMDVSEDQLKRAMEKIEEGLRKSYERGYISEDPEKVLKRIEATADLIEVAKDADLVIEAIPEIFDLKKKVFSEIEQYCPDHTIFATNTSSLSITKLAEATKRPEKFIGMHFFNPPKILKLLEIVWGEKTSEETIRIVEDFARKIDRIIIHVRKDVPGFIVNRIFVTMSNEASWAVEMGEGTIEEIDSAVKYRLGLPMGLFELHDVLGGGSVDVSYHVLEYYRQTLGESYRPSPLFERLFKAGHYGKKTGKGFYDWSEGKTNEVPLRAGANFDLLRLVAPAVNEAAWLIEKGVASAEEIDLAVLHGLNYPRGLLRMADDFGIDSIVKKLNELYEKYNGEERYKVNPVLQKMVEEGKLGRTTGEGFYKYGD";

static const char seq19[] =
"MKVKKVCVLGAGAMGSGIAQVCATAGYEVWVRDIKQEFLDRGKAAIEKNLQKAVSKGKMTEEKAKEILSRIHFTLDMEEAVKDADLVIEAVPEIMDLKKQVFAEVQKYAKPECIFASNTSGLSITELGNATDRPEKFLGLHFFNPPPVMALVEVIKGEKTSDETIKFGVEFVKSLGKVPVVVKKDVAGFIVNRILVPYLVLAIDDVEKGVATKEEIDATMMYKYGFPMGPIELSDFVGLDILYHASQQWDIVPQSKLLEEKFKANELGMKTGKGFYDWSAGRPKIPQELAGKYDAIRLIAPMVNIAADLIAMGVADAKDIDTAMKLGTNMPKGPCELGDEIGLDVILAKVEELYKEKGFEILKPSEHLKKMVSEGKLGEKSGEGFYSYGK";

static const char seq47[] = 
"MLLLPSRGKLYVVGIGPGKEELMTLKAKRAIEEADYIVGYQTYVDRISHLIEGKKVVTTPMRKELDRVKIALELAKEHVVALISGGDPSIYGILPLVIEYAVEKKVDVEIEAIPGVTAASAASSLLGSAISGDFAVVSLSDLLVPWSVVEKRLLYALSGDFVVAIYNPSSRRRKENFRKAMEIVRRFRGDAWVGVVRNAGREGQQVEIRRVSEVDEVDMNTILIVGNSETKVVDGKMFTPRGYSNKYNIG";

static const char seq1576[] =
"DQADMVRRVKNYENGFINNPIVISPTTTVGEAKSMKEKYGFAGFPVTADGKRNAKLVGAITSRDIQFVEDNSLLVQDVMTKNPVTGAQGITLSEGNEILKKIKKGRLLVVDEKGNLVSMLSRTDLMKNQKYPLASKSANTKQLLWGASIGTMDADKERLRLLVKAGLDVVILDS";

static const char seq1800[] =
"NPIVISPTTTVGEAKSMKERFGFSGFPVTEDGKRNGKLMGIVTSRDIQFVEDNSLLVQDVMTKNPVTGAQGITLSEGNEILKKIKKGKLLIVDDNGNLVSMLSRTDLMKN";

static const char seq_original1[] =
"MGDSSKKVKDSFDTISEPDSFDEPKGVPISMEPVFSTAAGIRIDVKQESIDKSKKMLNSDLKSKSSSKGG"
"FSSPLVRKNNGSSAFVSPFRREGTSSTTTKRPASGGFEDFEAPPAKKSTSSSSKKSKKHSKKEKKKEFKE"
"IHADVLRVSRIYEKDKFRIILQESSSTPLILATCSYNRGSDIKFGDRIHVDAEVCKKSSSGDVTEIYIDR"
"VLKNKENGAKSGIRRHSIAKKPFCIKPRFIHELSDTKIKKTVVQVNLLDLNLDFYAGCSKCKHSLPEAAN"
"QCEFCKDSQGKSELSMYSRVRVMDFSGQMFINVTTKNMKKLLDLLGYEGFDNWFRFKDPQERQNYVFRPV"
"MVEIEKSNDEWECTDVAEVDWKDFGSYLKHKEDKKKRRSKKKHP";

static const char seq_original2[] =
"MADVALRITETVARLQKELKCGICCSTYKDPILSTCFHIFCRSCINACFERKRKVQCPICRSVLDKRSCR"
"DTYQITMAVQNYLKLSEAFKKDIENMNTFKSLPPEKMFMESQMPLDITIIPENDGKRCAPDFAIPFLPVR"
"RKRPSRPQPPSAFAEEPAEPVEPPEPATKQPVELQSRVFPLEKLKKDVETSTETYKISREELKNVDIEEY"
"INTLRENSTEIDEIDALFQLMPTMRQFLRNNINQLMEKFHVAPPKKSEKPANRRVSFASSQDLENIKIMT"
"ASESLETPPEPIQKLAQKPEVFKSTQNLIDLNLNTAVKKPVVVASDDDEVVEDSEGELQIDEDDLANVTC"
"ATSVRNIGKSLCAEYIREGRSISQKSTAYLYAIARKCVIVGRQWLVDCITTGLLLSEADYTITSCSSTIP"
"VKIPPSIGSEMGWLRSRNDEHGKLFAGRRFMILRKFTMNPYFDYKQLIELVQQCGGEILSCYENLSPEKL"
"YIIFSKHSKAIEESKNIENLYKCDVVTMEWVLDSISEYLILPTQPYKAVDSIGCLQD";

int test(const char *seq1, const char *seq2)
{
    cell_t **tbl = NULL;
    int **del = NULL;
    int **ins = NULL;
    size_t seq1_len = strlen(seq1);
    size_t seq2_len = strlen(seq2);
    int max_seq_len = seq1_len > seq2_len ? seq1_len : seq2_len;
    cell_t result;
    param_t param;
    int is_edge_answer = 0;
    int sscore;
    size_t maxLen;
    sequence_t s1 = {"",seq1,seq1_len};
    sequence_t s2 = {"",seq2,seq2_len};

    assert(NROW == 2);
    tbl = pg_alloc_tbl(NROW, max_seq_len);
    del = pg_alloc_int(NROW, max_seq_len);
    ins = pg_alloc_int(NROW, max_seq_len);

    pg_affine_gap_align_blosum(&s1, &s2, &result, tbl, del, ins, -10, -1);
    param.AOL = 8;
    param.SIM = 4;
    param.OS = 3;
    is_edge_answer = pg_is_edge(result, &s1, &s2, param, &sscore, &maxLen);
    printf("---------------------------------------------------\n");
    printf("result->score=%d\n", result.score);
    printf("result->ndig=%d\n", result.ndig);
    printf("result->alen=%d\n", result.alen);
    printf("is_edge_answer=%d\n", is_edge_answer);
    printf("alen/maxLen=%f\n", 1.0*result.alen/maxLen);
    printf("nmatch/alen=%f\n", 1.0*result.ndig/result.alen);
    printf("score/sscore=%f\n", 1.0*result.score/sscore);

    pg_free_tbl(tbl, NROW);
    pg_free_int(del, NROW);
    pg_free_int(ins, NROW);

    return 0;
}


int main(int argc, char **argv)
{
    //test(seq_original1, seq_original2);
    //test(seq0, seq19);
    //test(seq0, seq47);
    test(seq1576, seq1800);
    return 0;
}
